version: '3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
#    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      front_net:
        aliases:
          - ui
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
#    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
    depends_on:
      - post_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
#    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  front_net:
  back_net:
